In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/Users/ISRAEL/Downloads/energydata_complete.csv')
df.head(4)

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  

[4 rows x 29 columns]

In [3]:
# Renaming columns

column_names={'T1':'TempKitchen_area', 'RH_1':'HumidityKitchen_area', 'T2':'TempLiving_area', 'RH_2':'HumidityLiving_area', 'T3':'TempLaundry_room_area', 'RH_3':'HumidityLaundry_room_area', 'T4':'TempOffice_room', 'RH_4':'HumidityOffice_room', 'T5':'TempBath_room', 'RH_5':'HumidityBath_room', 'T6':'TempOutside_building', 'RH_6':'HumidityOutside_building', 'T7':'TempIroning_room', 'RH_7':'HumidityIroning_room', 'T8':'TempTeenager_room', 'RH_8':'HumidityTeenager_room', 'T9':'TempParents_room', 'RH_9':'HumidityParents_room'}
df = df.rename(columns=column_names)
df.head(4)

date  Appliances  lights  TempKitchen_area  \
0  2016-01-11 17:00:00          60      30             19.89   
1  2016-01-11 17:10:00          60      30             19.89   
2  2016-01-11 17:20:00          50      30             19.89   
3  2016-01-11 17:30:00          50      40             19.89   

   HumidityKitchen_area  TempLiving_area  HumidityLiving_area  \
0             47.596667             19.2            44.790000   
1             46.693333             19.2            44.722500   
2             46.300000             19.2            44.626667   
3             46.066667             19.2            44.590000   

   TempLaundry_room_area  HumidityLaundry_room_area  TempOffice_room  ...  \
0                  19.79                  44.730000        19.000000  ...   
1                  19.79                  44.790000        19.000000  ...   
2                  19.79                  44.933333        18.926667  ...   
3                  19.79                  45.000000        18.890000  ...   

   TempParents_room  HumidityParents_room     T_out  Press_mm_hg  RH_out  \
0         17.033333                 45.53  6.600000        733.5    92.0   
1         17.066667                 45.56  6.483333        733.6    92.0   
2         17.000000                 45.50  6.366667        733.7    92.0   
3         17.000000                 45.40  6.250000        733.8    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410389  45.410389  

[4 rows x 29 columns]

In [7]:
# Question 12

from sklearn.linear_model import LinearRegression

# Getting the required columns
dfregr = df[['TempLiving_area','TempOutside_building']]

# Fitting into the model
model = LinearRegression()

model.fit(dfregr[['TempLiving_area']], dfregr[['TempOutside_building']])

predicted = model.predict(dfregr[['TempLiving_area']])

# Getting Rsquared in two decimal places
from sklearn.metrics import r2_score

Rsquared = r2_score(dfregr[['TempOutside_building']], predicted)

print(round(Rsquared, 2))

0.64


In [9]:
# Questions 13 - 20

# Getting required columns
df_dropped = df.drop(columns=['date', 'lights'])

# Importing MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled = pd.DataFrame(scaler.fit_transform(df_dropped), columns=df_dropped.columns)

# Getting the independent and dependent variables
predictors = scaled.drop(columns=['Appliances'])
target = scaled['Appliances']

# Splitting the data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=42)

# Fitting into the model
linear_model = LinearRegression()

linear_model.fit(x_train, y_train)

predicted_values = linear_model.predict(x_test)

print(predicted_values)

[0.03322207 0.24411599 0.03400024 ... 0.06844707 0.10032325 0.05722198]


In [10]:
# Question 13

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, predicted_values)
print(round(mae, 2))

0.05


In [12]:
# Question 14

rss = np.sum(np.square(y_test - predicted_values))
print(round(rss, 2))

45.35


In [13]:
# Question 15

from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
print(round(rmse, 3))

0.088


In [14]:
# Question 16

from sklearn.metrics import r2_score

rsquared =  r2_score(y_test, predicted_values)
print(round(rsquared, 2))

0.15


In [15]:
# Question 17

# Getting weights

def get_weights(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

lmw = get_weights(linear_model, x_train, 'Linear_Model_Weight')
print(lmw)

                     Features  Linear_Model_Weight
0         HumidityLiving_area            -0.456698
1                       T_out            -0.321860
2             TempLiving_area            -0.236178
3            TempParents_room            -0.189941
4       HumidityTeenager_room            -0.157595
5                      RH_out            -0.077671
6        HumidityIroning_room            -0.044614
7        HumidityParents_room            -0.039800
8               TempBath_room            -0.015657
9            TempKitchen_area            -0.003281
10                        rv2             0.000770
11                        rv1             0.000770
12                Press_mm_hg             0.006839
13           TempIroning_room             0.010319
14                 Visibility             0.012307
15          HumidityBath_room             0.016006
16        HumidityOffice_room             0.026386
17            TempOffice_room             0.028981
18                  Windspeed  

In [17]:
# Question 17

# Getting lowest and highest weights

print(lmw[(lmw['Linear_Model_Weight'] == lmw['Linear_Model_Weight'].min())])
print(lmw[(lmw['Linear_Model_Weight'] == lmw['Linear_Model_Weight'].max())])

# HumidityLiving_area = RH_2
# HumidityKitchen_area = RH_1

              Features  Linear_Model_Weight
0  HumidityLiving_area            -0.456698
                Features  Linear_Model_Weight
25  HumidityKitchen_area             0.553547


In [19]:
# Question 18

# Getting ridge regression model values using alpha value of 0.4

from sklearn.linear_model import Ridge

ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)

predicted_ridge = ridge_reg.predict(x_test)
print(predicted_ridge)

[0.03321872 0.24043824 0.03461337 ... 0.06872351 0.10025536 0.05851175]


In [22]:
# Question 18

# Finding the RMSE

rmse_ridge = np.sqrt(mean_squared_error(y_test, predicted_ridge))
print(round(rmse_ridge, 3))

# RMSE values are similar
# Answer = No

0.088


In [23]:
# Question 19

# Getting Lasso regression model with alpha value of 0.001

from sklearn.linear_model import Lasso

lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)

predicted_lasso = lasso_reg.predict(x_test)
print(predicted_lasso)

[0.07370267 0.08143458 0.07716072 ... 0.07792848 0.09034412 0.08359255]


In [25]:
# Question 19

# Getting weights

def get_weights(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

lmw_lasso = get_weights(lasso_reg, x_train, 'Linear_Model_Weight')

print(lmw_lasso)

# Number of features with non-zero weights = 4

                     Features  Linear_Model_Weight
0                      RH_out            -0.049557
1       HumidityTeenager_room            -0.000110
2            TempKitchen_area             0.000000
3                   Tdewpoint             0.000000
4                  Visibility             0.000000
5                 Press_mm_hg            -0.000000
6                       T_out             0.000000
7        HumidityParents_room            -0.000000
8            TempParents_room            -0.000000
9           TempTeenager_room             0.000000
10       HumidityIroning_room            -0.000000
11                        rv1            -0.000000
12           TempIroning_room            -0.000000
13       TempOutside_building             0.000000
14          HumidityBath_room             0.000000
15              TempBath_room            -0.000000
16        HumidityOffice_room             0.000000
17            TempOffice_room            -0.000000
18  HumidityLaundry_room_area  

In [26]:
# Question 20

rmse_lasso = np.sqrt(mean_squared_error(y_test, predicted_lasso))
print(round(rmse_lasso, 3))

0.094
